#Sat Jan 04 16:57:07 UTC 2025
datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: tbs

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

micronaut:
  application:
    name: demo

